create table if not exists users_t
(
    id         bigint generated by default as identity,
    created_at timestamp(6) with time zone,
    email      varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    password   varchar(255) not null,
    role       integer      not null,
    status     integer      not null,
    primary key (id)
);

DO '
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = ''users_email_unique''
    ) THEN
ALTER TABLE users_t
    ADD CONSTRAINT users_email_unique UNIQUE (email);
END IF;
END
';

INSERT INTO users_t (id, created_at, email, first_name, last_name, password, role, status)
VALUES
    (1, CURRENT_TIMESTAMP, 'employee@example.com', 'Ivan', 'Krylosov',
     '$2a$10$H/lo2LyEXyJgVMZ0RbUX6eb8R9S7GzuPPMEDpAdGiQj9aOnlhShyy', -- 12345678
     1, 1)
    ON CONFLICT (email) DO NOTHING;

INSERT INTO users_t (id, created_at, email, first_name, last_name, password, role, status)
VALUES
    (2, CURRENT_TIMESTAMP, 'visitor@example.com', 'Ivan', 'Krylosov',
     '$2a$10$H/lo2LyEXyJgVMZ0RbUX6eb8R9S7GzuPPMEDpAdGiQj9aOnlhShyy', -- 12345678
     0, 1)
    ON CONFLICT (email) DO NOTHING;

SELECT setval(pg_get_serial_sequence('users_t', 'id'), COALESCE(MAX(id) + 1, 1), false)
FROM users_t;

